# Site settings
title: ELITES
email: 
description: >- # this means to ignore newlines until "baseurl:"
  
# url: "https://noopy0415.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/test_pages_2" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
# github_username: noopy0415

# サポートしているテーマ https://pages.github.com/themes/
# Build settings
theme: minima
# theme: jekyll-theme-slate
#theme: jekyll-theme-cayman
# theme: jekyll-theme-midnight
# theme: jekyll-theme-slate
# theme: jekyll-theme-minimal


plugins:
  - jekyll-feed
  - "jekyll-github-metadata"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: GFM

# kramdown:
#    input: GFM
#    hard_wrap: false
